require:
  - rubocop-minitest
  - rubocop-performance
  - rubocop-sorbet

AllCops:
  NewCops: enable
  Exclude:
    - 'example.rb'
    - 'tmp/*'
    - 'vendor/**/*'

Lint/ToJSON:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Lint/MissingSuper:
  Enabled: false

# Wait until https://github.com/rubocop/rubocop/issues/8761 is fixed
Gemspec/RequiredRubyVersion:
  Enabled: false

Minitest/MultipleAssertions:
  Enabled: false

Style/AccessorGrouping: # disabled so that we can use sorbet signatures for each attr
  Enabled: false 

